### ISSUE TITLE
Any major update soon?

### ISSUE THREAD

**Issue by ctzurcanu** [rwb27/openflexure_microscope#100]
I would like to present this device to a conference and I want to make sure that I get to build the best-updated thing. Should I wait 2-3 weeks or should I begin as soon as I can access a 3D printer with the present models?

**Comment by rwb27** [comment]
I think the latest release is the best one to use - this rolls together all the latest updates and has some reasonably complete documentation.  We're not planning anything bar bug fixes for the next little while, we're focusing on getting the software right.
