### ISSUE TITLE
No instructions about sample riser

### ISSUE THREAD

**Issue by jtc42** [rwb27/openflexure_microscope#110]

**Comment by sctv** [comment]
hi @jtc42 
Can you expand the issue a bit.  
What do you want to know about the sample riser?
Are you using it in a build of an open flexure microscope?  
Cheers,
Brian

**Comment by rwb27** [comment]
It's now mentioned in the final assembly page in the instructions, as of 1409567aa4b7cada70bdada6e3233dbf6cbc6208

The sample riser simply raises the sample up 10mm, allowing the use of a longer microscope objective - I now mostly use better-corrected, 45mm parfocal objectives (the smaller, cheaper ones are 35mm parfocal).
