### ISSUE TITLE
Ability to change heigh of objective

### ISSUE THREAD

**Issue by dborgesr** [rwb27/openflexure_microscope#27]
Hey, firstly i wanted to say incredible project! i've already printed and built 3 microscopes. 
I've already tried to get the RMS objective version working but ran into the issue that the objectives themselves are not all a standard height.

I know this request is way far out (i'm currently learning Fusion 360 to help out with the implementation), but I was wondering, would there be a way to make the height of the lens assembly tunable? Maybe have some sort of rung system built into the slide that's already present or something of the sort, this would allow immediate use of any objectives, even cheap ones you can buy off amazon, making this microscope ready for prime time.

--Cheers

**Comment by rwb27** [comment]
Hey,
  always great to hear from someone who's built it!  I've found two common objective sizes, which are 25mm and 35mm (this is the "parfocal distance", measured from "shoulder" at the top of the thread on the objective to the sample (which may or may not be more or less the same place as the top of the objective).  The LS65 stage and the optics modules in the STL folder are set up for 25mm objectives.  To work with 35mm objectives, I usually use the same set-up, but add a [10mm thick spacer](https://github.com/rwb27/openflexure_microscope/blob/master/stl/sample_riser_2_base.stl) on top of the stage to raise the sample.  The one I linked to has a handy sprung [clip](https://github.com/rwb27/openflexure_microscope/blob/master/stl/sample_riser_2_clip.stl) to keep the sample in place.  Alternatively you can use an LS75 stage, which is 10mm higher.  NB you also need the [LS75 illumination](https://github.com/rwb27/openflexure_microscope/blob/master/builds/illumination_and_back_foot_condenser_LS75.stl), which is taller.

  For more fine-tuning, it's relatively easy to adjust the spacing of things in the [optics module source](https://github.com/rwb27/openflexure_microscope/blob/master/openscad/optics.scad), the ``objective_parfocal_distance`` argument allows you to set the distance from the top of the mount to the sample.  This relies on having microscope_parameters set up correctly to match the microscope you're trying to build.

Any of that make sense?  I've not found a nice way to get serious adjustment of things like parfocal distance with one plastic part, instead I'm embracing the joys of parametric CAD and doing the adjustment before it's printed - but if you can come up with a solution, that's great.
