### ISSUE TITLE
Documentation of OpenSCAD files

### ISSUE THREAD

**Issue by Sammy93** [rwb27/openflexure_microscope#29]
Hi Richard,

Can you please provide description of which .scad files are responsible for the microscope design and also how they can be combined together to render the microscope. 

Thanks,
Sammy

**Comment by rwb27** [comment]
I've now added a readme to the ``OpenSCAD`` and ``OpenSCAD/cameras`` folders in 6ab43e27c25814e4824bc2882efced86786b30bc and a7cec7709f509dd44f41814d1c74dc3430fb404a, which explains which file makes which piece.  There should already be a reasonable amount of comment inside each file, so I'm hoping this is the missing link.  Let me know if that makes things clear, and do re-open the issue if it doesn't!
