### ISSUE TITLE
M3 Thumbwheel Screws - 6 Nut Issue & Solution

### ISSUE THREAD

**Issue by SuAdams** [rwb27/openflexure_microscope#63]
Last week 2 adults, who will be mentoring youth at the event, built the microscope. Subsequently 2 14 year olds tested the build at the weekend.  

Both times the pairs experienced the same problem; when trying to focus the image, the centre thumbwheel unwound.  

I have adjusted the instructions for our version (which uses 6 nuts in the actuator build) to use 2 x 25mm M3 screws on the outer thumbwheels, and 1 x 30mm M3 screw for the centre thumbwheel.  This appears to resolve the problem nicely.

**Comment by rwb27** [comment]
Thanks for that - I've included that in the documentation in 2688ac6.  If you felt like updating the [wiki page](https://github.com/rwb27/openflexure_microscope/wiki/Non-printed-parts) that would also be brilliant :)
