### ISSUE TITLE
printing microscope on an unknown printer

### ISSUE THREAD

**Issue by Sammy93** [rwb27/openflexure_microscope#65]
printing the microscope with a raft on an unknown printer (or printer which has poor bed levelling) significantly improves the success rate of the print however there are some issues with the holes at the bottom.

**Comment by rwb27** [comment]
thanks - it's definitely going to help it to stick, my worry is that bits get broken when you remove the raft.  Did you manage to do that?  I think I'll close this issue for now, but it's always helpful to have stuff logged.
