### ISSUE TITLE
baseplate mount holes fused with stage on SS40, v5.17.1-5540

### ISSUE THREAD

**Issue by Sammy93** [rwb27/openflexure_microscope#66]
![image](https://user-images.githubusercontent.com/3144547/35739503-b0fad248-0829-11e8-9e39-c34f171194a5.png)

As a result, the stage is stiffer and X/Y travel is decreased.

**Comment by rwb27** [comment]
Thanks for the nice clear photo.  I don't know when this happened, but I have now fixed it in 9fe004d427fbe358df5adee427e7eb3ab92424ce.  Sorry for the wasted print...
