### ISSUE TITLE
Feet.stl has middle foot too low 

### ISSUE THREAD

**Issue by paulnyakyi** [rwb27/openflexure_microscope#74]
Middle foot start printing first, and the other feet try to start on the second layer, stopping the print from working.
![image](https://user-images.githubusercontent.com/22287623/41524751-2925d812-72e7-11e8-9397-e72b2721e254.png)

**Comment by julianstirling** [comment]
This is for the cantilevered branch not master.

**Comment by rwb27** [comment]
good spot - that explains why my feet weren't sticking to the bed properly!  I'll fix the coordinate transforms, that's likely the problem.
