### ISSUE TITLE
New illumination adjustment screws need nuts

### ISSUE THREAD

**Issue by julianstirling** [rwb27/openflexure_microscope#76]
After a few adjustments of the illumination the M3 bolt which just taps into the base becomes loose and cannot be tightened. Can nut slots be added into the STL for the base?

**Comment by rwb27** [comment]
Upgraded to the better triangular self-tapping holes, and added nut traps - they might not always get used, but the option is there, at least.  Currently there's no nut in the instructions, that's probably fine for now.
