### ISSUE TITLE
Objective hits hole in stage

### ISSUE THREAD

**Issue by rwb27** [rwb27/openflexure_microscope#84]
The high-res version has a 30mm hole in the middle, but the nicer objectives are nearly 25mm in diameter - which limits the travel.

As and when this gets fixed, I will also need to sort out the endstops.

**Comment by codeTom** [comment]
I have a version with larger hole, but I had to modify the rectangular hole underneath, its width is now hole diameter+2mm, UM3 printed these bridge fine with hole_r=19.5 see b9b09c8744aca0b5a74177f91af5fefd1c1fc4c1

**Comment by rwb27** [comment]
This will go into the release very soon - I think it's fixed, though we might need to update the sample riser as well.

**Comment by rwb27** [comment]
Sample riser is also fixed, marking this as done.
