### ISSUE TITLE
optics module dovetail missing nut slot lip

### ISSUE THREAD

**Issue by codeTom** [rwb27/openflexure_microscope#86]
The lip holding the nut in the optics module is missing (is very small in the model), due to the change in 69a7df3b0526fe402e57e8414f581b26b9ee34f5 .

**Comment by rwb27** [comment]
Fixed in the latest development branch (e39d4d8d6fdb53d90a1efa69ab2c1e32b5ddd85c), but I should probably revert the offending commit on that branch for posterity.
