### ISSUE TITLE
http://rwb27.github.io/openflexure_microscope/builds gives 404

### ISSUE THREAD

**Issue by sctv** [rwb27/openflexure_microscope#95]
In the documentation/pages webpage on rwb27.github.io from the printing instructions, [http://rwb27.github.io/openflexure_microscope/docs/0_printing.html](http://rwb27.github.io/openflexure_microscope/docs/0_printing.html) the build directory is incorrectly linked or non-existent 
this is the target [http://rwb27.github.io/openflexure_microscope/builds](http://rwb27.github.io/openflexure_microscope/builds) 

On the github website the link from the file [https://github.com/rwb27/openflexure_microscope/blob/master/docs/0_printing.md](https://github.com/rwb27/openflexure_microscope/blob/master/docs/0_printing.md) to [(https://github.com/rwb27/openflexure_microscope/tree/master/builds](https://github.com/rwb27/openflexure_microscope/tree/master/builds)

I don't understand as the pages one/github.io is built from the github.com page, perhaps the stl directory isn't replicated?

**Comment by rwb27** [comment]
Thanks for spotting that - you are dead right, it's a relative link and I didn't copy over the builds/ directory.  I think it is probably more helpful to keep the relative link, but add a redirect, which I have tried to do.  The redirect doesn't seem to actually work, unfortunately, I'm not sure why, but at least there is now a helpful link. (I don't think Jekyll will give you a helpful index display of all the files).

I should probably also point out that you can get the files from the latest release...

It's not perfect, but I think it's good enough for now - no point sinking too much effort in here as I very much hope our build server will go live before too long (I'm already building there - just need to set up HTTP to serve the files to the world).

If you could verify the link now works for you, that would be super - I'll close the issue as I think it's sorted, but please do re-open it if I've missed something.
