### ISSUE TITLE
http://rwb27.github.io/openflexure_microscope/docs/parts/d13_f50_achromat gives 404 error

### ISSUE THREAD

**Issue by ctzurcanu** [rwb27/openflexure_microscope#99]
when clicked from page http://rwb27.github.io/openflexure_microscope/docs/2b_high_resolution_optics_module.html

**Comment by rwb27** [comment]
Hi @ctzurcanu thanks - currently the bill of materials (which includes the contents of the ``parts`` folder) is a bit of a work in progress - the intention is that it will be fully populated but I'm not quite there yet.   The part in question is an achromatic lens, with a focal length of 50mm and a diameter of 13mm (or more precisely, 12.7mm).  The easiest way to get hold of one is to order it from ThorLabs, as part number AC127-050-A.

If you are just checking out the project, it might be easier to start with the basic optics module - this is much cheaper and in particular doesn't need any specialist optics, just the Raspberry Pi camera module.

**Comment by rwb27** [comment]
I have done my best to keep the bill of materials reasonably complete in the first section of the instructions (perhaps confusingly named "printing").  I hope I've described things fully enough there, but I will try to add some more information on the specialist parts.

**Comment by ctzurcanu** [comment]
We really want to make something not only sensational but hopefully useful for Medicine. That is why we opted for maximum magnification that we could demo.

I found the part there for about 50 Eur. Will buy.

**Comment by rwb27** [comment]
cool - do let us know how the build goes!
